version: 'Compose specification'
services:
  app:
    build: .
    volumes:
      - .:/django-app
    ports:
      - 8000:8000
    image: app:django-app
    container_name: django_container
    command: >
      sh -c "
        python manage.py loaddata db.json &&
        python manage.py migrate &&
        python manage.py runserver --settings=oc_lettings_site.settings 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - /data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
