version: '3.0'
services:
  app:
    build: .
    volumes:
      - .:/django-app
    ports:
      - 8000:8000
    image: python-oc-lettings:django-app
    container_name: django_container
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver --settings=oc_lettings_site.settings 0.0.0.0:8000"
