version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  lint-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
          env:
            SECRET_KEY: $DJANGO_SECRET_KEY
      - run:
          name: Flake8
          command: flake8 --config='./setup.cfg'

workflows:
  dev:
    jobs:
      - lint-and-test