version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.2

jobs:
  lint-and-test:
    executor: python/default
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Flake8
          command: flake8 --config='./setup.cfg'
      - run:
          name: Run tests
          command: pytest
          environment:
            DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
            NAME: $NAME
            USER: $USER
            PASSWORD: $PASSWORD
            HOST: $HOST
            PORT: $PORT

workflows:
  dev:
    jobs:
      - lint-and-test
