version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.2

jobs:
  lint-and-test:
    docker:
      - image: friquette/python-oc-lettings:django-app
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Flake8
          command: flake8 --config='./setup.cfg'
      - run:
          name: Run tests
          command: pytest
          environment:
            DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY

workflows:
  dev:
    jobs:
      - lint-and-test
